import 'package:flutter/material.dart';

class EmojiList extends StatefulWidget {
  const EmojiList({Key? key, this.onPick, this.controller}) : super(key: key);

  final void Function(String emoji)? onPick;
  final ScrollController? controller;

  @override
  _EmojiListState createState() => _EmojiListState();
}

class _EmojiListState extends State<EmojiList> {
  @override
  Widget build(BuildContext context) {
    return GridView.builder(
        controller: widget.controller,
        itemCount: _listEmoji.length,
        gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
            crossAxisCount: 7, crossAxisSpacing: 10),
        itemBuilder: (BuildContext context, int index) {
          return GestureDetector(
            onTap: () {
              String? emoji = _mapEmoji[_listEmoji[index]];
              if (emoji != null && widget.onPick != null) {
                widget.onPick!(emoji);
              }
            },
            child: Center(
              child: Image.asset('assets/icons/' + _listEmoji[index] + '.png'),
            ),
          );
        });
  }
}

final _listEmoji = [
  'smile',
  'boring',
  'love',
  'smilecry',
  'cool',
  'cry',
  'bigeye',
  'cutesmile',
  'sleep',
  'cry2',
  'confuse',
  'angry',
  'kidding',
  'bigsmile',
  'suprice',
  'disapoint',
  'badsmile',
  'foo',
  'coolsmile',
  'windkiss',
  'handsmile',
  'comfo',
  'bashful',
  'question',
  'look',
  'mlem',
  'tired',
  'redsuprice',
  'stingy',
  'laugh',
  'coolsmoke',
  'fighting',
  'chiav',
  'howling',
  'luffy',
  'please',
  'hismile',
  'huh',
  'wel',
  'yaw',
  'blame',
  'what',
  'shhh',
  'dizzy',
  'sanji',
  'bombed',
  'skull',
  'bonk',
  'hello',
  'badidea',
  'guity',
  'sad',
  'ahhh',
  'heheh',
  'chuu',
  'wwhaaat',
  'pleasee',
  'nocomment',
  'cantsay',
  'uoee',
  'smash',
  'zoro',
  'money',
  'beer',
  'coffee',
  'rose',
  'sadrose',
  'kill',
  'bomb',
  'birth',
  'heart',
  'heartbreak',
  'dumb',
  'bolt',
  'vietnam',
  'like',
  'dislike',
  'ok',
  'hi',
  'thankful',
  'punch',
  'friendly',
  'please2',
  'just',
  'promise',
  'bro',
  'redboring',
  'thief',
  'comehere'
];

final Map<String, String> _mapEmoji = {
  'smile': ':)',
  'boring': ':~',
  'love': ':b',
  'smilecry': ':\')',
  'cool': '8-)',
  'cry': ':-((',
  'bigeye': ':\$',
  'cutesmile': ':3',
  'sleep': ':z',
  'cry2': ':((',
  'confuse': '&-(',
  'angry': ':-h',
  'kidding': ':p',
  'bigsmile': ':d',
  'suprice': ':o',
  'disapoint': ':(',
  'badsmile': ';-)',
  'foo': '--b',
  'coolsmile': ':))',
  'windkiss': ':-*',
  'handsmile': ';p',
  'comfo': ';-d',
  'bashful': '/-showlove',
  'question': ';d',
  'look': ';o',
  'mlem': ';g',
  'tired': '|-)',
  'redsuprice': ':!',
  'stingy': ':l',
  'laugh': ':>',
  'coolsmoke': ':;',
  'fighting': ';f',
  'chiav': ':v',
  'howling': ':wipe',
  'luffy': ':-dig',
  'please': ':handclap',
  'hismile': 'b-)',
  'huh': ':-r',
  'wel': ':-<',
  'yaw': ':-o',
  'blame': ';-s',
  'what': ';?',
  'shhh': ';-x',
  'dizzy': ':-f',
  'sanji': '8*)',
  'bombed': ';!',
  'skull': ';-!',
  'bonk': ';xx',
  'hello': ':-bye',
  'badidea': '>-|',
  'guity': 'p-(',
  'sad': ':--|',
  'ahhh': ':q',
  'heheh': 'x-)',
  'chuu': ':*',
  'wwhaaat': ';-a',
  'pleasee': '8*',
  'nocomment': ':|',
  'cantsay': ':x',
  'uoee': ':t',
  'smash': ';-/',
  'zoro': ':-l',
  'money': '\$-)',
  'beer': '/-beer',
  'coffee': '/-coffee',
  'rose': '/-rose',
  'sadrose': '/-fade',
  'kill': '/-bd',
  'bomb': '/-bome',
  'birth': '/-cake',
  'heart': '/-heart',
  'heartbreak': '/-break',
  'dumb': '/-shit',
  'bolt': '/-li',
  'vietnam': '/-flag',
  'like': '/-strong',
  'dislike': '/-weak',
  'ok': '/-ok',
  'hi': '/-v',
  'thankful': '/-thanks',
  'punch': '/-punch',
  'friendly': '/-share',
  'please2': '_()_',
  'just': '/-no',
  'promise': '/-bad',
  'bro': '/-loveu',
  'redboring': '/-redboring',
  'thief': '/-thief',
  'comehere': '/-come',
};

Map<String, String> getEmojiList() {
  return _mapEmoji;
}
